# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HjXII5PdEDXUGN5rZR92TWRd9KLTOIzHI8EHUhQs5Fc9IMyrKR+voVlflW0pNCX1qelOpd6wAZ5CmOOHTi4sW1cZZ5vrLMs+eHd1A5eXWXewE6LoZMAlSWcdWDQzYRubA0CgEQruTOCxMaqsSvDw3dzCVPQEm5Vca1b6zqI/1A6nEa+pfEMaxMg86bpJUlrL4ZxAsDkL8wholMKwXlOahjM6EFazqfpLAPEKN2K/sGAq28aqDiuQpu0/y1cLflQWeI/Qq8s0fCHp9Us1Lhr6F10lJKVfepCBeB77tLgsneYxgt7JJe2prhmUlXR9M9Ix6j0dPpO5oxvQQn4DTXtdSGR95eSMP4ib3Ysqc6cEYgg5QX/e0Ob5QhIZ9j/yyDq2fm5JELyYFbMxnc3n7U4i0BwCIbSciCFVqF9WyhgyOwMYw5+WxDAFH5obmeecXxeMVHbSu3oiaENwNWlDPPOQWCQzh3CZdzi1uvBvkFxJgF0nFndWZ8D+WMWqUDO3hb9e94QEXQwA68nKoEE7tM9zXpYa9RJ2VLXKzC2VOV+6tRdwo95cIhQ40iW6AkmDdnoa5uKthEtvIEgjBMpn2gwXsm5FmmjMmN0wGn672Ozn56G0+gwh1ER0yQLkTfv/O2W7stidW1BwH8Hj1KxLrFMNvR7oEGWIHLrDHk2+DbH5+TE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
